discovery:
  image: iteris/poc-accesstage-eureka-server
  ports:
   - "8761:8761"
authentication:
  image: iteris/poc-accesstage-authentication
  links:
   - discovery
  ports:
   - "8081:8081"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
proxy:
  image: iteris/poc-accesstage-proxy
  links:
   - discovery
   - authentication
   - transaction
  ports:
   - "8090:8090"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
transaction:
  image: iteris/poc-accesstage-transaction
  links:
   - discovery
   - authentication
   - transaction-rede
  ports:
   - "8082:8082"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
transaction-rede:
  image: iteris/poc-accesstage-transaction-rede
  links:
   - discovery
  ports:
   - "8083:8083"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka