discovery:
  image: iteris/payment-gateway-discovery-server
  ports:
   - "8761:8761"
authentication:
  image: iteris/payment-gateway-authentication
  links:
   - discovery
  ports:
   - "8081:8081"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
proxy:
  image: iteris/payment-gateway-proxy
  links:
   - discovery
   - authentication
   - transaction
  ports:
   - "8090:8090"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
transaction:
  image: iteris/payment-gateway-transaction
  links:
   - discovery
   - authentication
   - transaction-rede
   - transaction-cielo
  ports:
   - "8082:8082"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
transaction-rede:
  image: iteris/payment-gateway-transaction-rede
  links:
   - discovery
  ports:
   - "8083:8083"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
transaction-cielo:
  image: iteris/payment-gateway-transaction-cielo
  links:
   - discovery
  ports:
   - "8084:8084"
  environment:
   - EUREKA_URI=http://discovery:8761/eureka
