authentication:
  ribbon:
    eureka:
      enabled: true

server:
  port: 8082

spring:
  application:
    name: transaction

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}