apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: payment-gateway
    role: authentication
    tier: backend
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: payment-gateway
    role: authentication
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-gateway
        role: authentication
        tier: backend
    spec:
      containers:
      - name: master
        image: iterisgsv/payment-gateway-authentication
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: EUREKA_INSTANCE_HOSTNAME
          value: authentication
        - name: EUREKA_URI
          value: http://discovery-server:8761/eureka
        ports:
        - containerPort: 8081