apiVersion: v1
kind: Service
metadata:
  name: postgres-database
  labels:
    app: payment-gateway
    role: database
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: payment-gateway
    role: database
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-gateway
        role: database
        tier: backend
    spec:
      containers:
      - name: master
        image: iterisgsv/payment-gateway-database
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
        env:
        - name: POSTGRES_PASSWORD
          value: rootpassword
        ports:
        - containerPort: 8761