apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: payment-gateway
    role: discovery
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: payment-gateway
    role: discovery
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-gateway
        role: discovery
        tier: backend
    spec:
      containers:
      - name: master
        image: iterisgsv/payment-gateway-discovery-server
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - containerPort: 8761