apiVersion: v1
kind: Service
metadata:
  name: transaction-cielo
  labels:
    app: payment-gateway
    role: transaction-cielo
    tier: backend
spec:
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: payment-gateway
    role: transaction-cielo
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transaction-cielo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-gateway
        role: transaction-cielo
        tier: backend
    spec:
      containers:
      - name: master
        image: iterisgsv/payment-gateway-transaction-cielo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: EUREKA_INSTANCE_HOSTNAME
          value: transaction-cielo
        - name: EUREKA_URI
          value: http://discovery-server:8761/eureka
        ports:
        - containerPort: 8084