apiVersion: v1
kind: Service
metadata:
  name: transaction
  labels:
    app: payment-gateway
    role: transaction
    tier: backend
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: payment-gateway
    role: transaction
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-gateway
        role: transaction
        tier: backend
    spec:
      containers:
      - name: master
        image: iterisgsv/payment-gateway-transaction
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: EUREKA_URI
          value: http://discovery-server:8761/eureka
        - name: EUREKA_INSTANCE_HOSTNAME
          value: transaction
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-database:5432/postgres
        ports:
        - containerPort: 8082